import { readdirSync } from "node:fs";
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import { unified } from "@astrojs/markdown-remark";
import starlight from "@astrojs/starlight";
import remarkStripWikilinks from "./site/plugins/remark-strip-wikilinks.mjs";
import remarkDropLeadingH1 from "./site/plugins/remark-drop-leading-h1.mjs";

// Starlight's autogenerated sidebar only looks under src/content/docs, so
// build the data source groups from the folders in docs/data_source.
const dataSourceSidebar = readdirSync("./docs/data_source", { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort((a, b) => a.localeCompare(b, "ja"))
  .map((provider) => ({
    label: provider,
    collapsed: true,
    items: readdirSync(`./docs/data_source/${provider}`)
      .filter((f) => f.endsWith(".md"))
      .map((f) => f.replace(/\.md$/, ""))
      .sort((a, b) => a.localeCompare(b, "ja"))
      .map((name) => ({ label: name, link: `/data_source/${provider}/${name}/` })),
  }));

// GitHub Pages supplies its origin and base path. Cloudflare Pages uses /.
// Local development defaults to the existing GitHub Pages location.
const site = process.env.ASTRO_SITE || process.env.CF_PAGES_URL || "https://unopengis.org";
const base = process.env.ASTRO_BASE ?? (process.env.CF_PAGES_URL ? "/" : "/foil4g/");

// Keep the reusable React maps in src/ and publish the documentation from site/.
export default defineConfig({
  site,
  base,
  srcDir: "./site",
  outDir: "./dist-site",
  integrations: [
    starlight({
      title: "FOIL4G",
      // site/pages/404.astro supplies a base-aware return link.
      disable404Route: true,
      locales: { root: { label: "日本語", lang: "ja" } },
      favicon: "/images/un-open-gis-smart-maps.jpg",
      sidebar: [
        { label: "切り口から探す", link: "/" },
        { label: "すべてのデータ", link: "/data_source/" },
        { label: "データソース", items: dataSourceSidebar },
      ],
      components: {
        MarkdownContent: "./site/components/MarkdownContent.astro",
        SocialIcons: "./site/components/SocialIcons.astro",
      },
    }),
    react(),
  ],
  vite: {
    build: {
      // MapLibre is a ~1 MiB lazy-loaded vendor chunk, used only on map cards.
      // Keep a 1.2 MiB budget rather than warning at the default 500 KiB.
      chunkSizeWarningLimit: 1200,
    },
  },
  markdown: {
    processor: unified({
      remarkPlugins: [remarkStripWikilinks, remarkDropLeadingH1],
    }),
  },
});
