import { readdirSync } from "node:fs";
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import starlight from "@astrojs/starlight";
import remarkStripWikilinks from "./site/plugins/remark-strip-wikilinks.mjs";
import remarkDropLeadingH1 from "./site/plugins/remark-drop-leading-h1.mjs";

// Starlight's autogenerated sidebar only looks under src/content/docs, so
// build the data source groups from the folders in docs/data_source.
const dataSourceSidebar = readdirSync("./docs/data_source", { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort((a, b) => a.localeCompare(b, "ja"))
  .map((provider) => ({
    label: provider,
    collapsed: true,
    items: readdirSync(`./docs/data_source/${provider}`)
      .filter((f) => f.endsWith(".md"))
      .map((f) => f.replace(/\.md$/, ""))
      .sort((a, b) => a.localeCompare(b, "ja"))
      .map((name) => ({ label: name, link: `/data_source/${provider}/${name}/` })),
  }));

// The Vite app and Storybook keep src/ and public/. The documentation site
// lives in site/ and builds to dist-site/, reading the cards from docs/.
export default defineConfig({
  srcDir: "./site",
  outDir: "./dist-site",
  integrations: [
    starlight({
      title: "FOIL4G",
      locales: { root: { label: "日本語", lang: "ja" } },
      favicon: "/images/un-open-gis-smart-maps.jpg",
      sidebar: [{ label: "データソース", items: dataSourceSidebar }],
      components: {
        MarkdownContent: "./site/components/MarkdownContent.astro",
        SocialIcons: "./site/components/SocialIcons.astro",
      },
    }),
    react(),
  ],
  markdown: {
    remarkPlugins: [remarkStripWikilinks, remarkDropLeadingH1],
  },
});
