name: lint

on:
  push:
  workflow_dispatch:

jobs:
  ollama:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh
      - name: Start serving
        run: |
            ollama serve &
            sleep 5
            time curl -i http://localhost:11434
      - name: Pull gemma2:2b
        run: |
            ollama pull gemma2:2b
      - name: Invoke gemma2:2b
        run: |
            ollama run gemma2:2b "Who is the current Secretary General of the United Nations?"
