name: ollama

on:
  push:
  workflow_dispatch:

jobs:
  ollama:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Make ollama models directory
        run: |
          mkdir -p ~/.ollama/models
      - name: Cache Ollama dir
        id: cache-ollama
        uses: actions/cache@v4
        with:
          path: |
            ~/.ollama
            ~/.ollama/models
          key: ${{ runner.os }}-ollama
      - name: Install Ollama
        env:
          OLLAMA_MODELS: ~/.ollama/models
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh
          sudo systemctl stop ollama.service
      - name: Start serving
        env:
          OLLAMA_MODELS: ~/.ollama/models
        run: |
            ollama serve &
            sleep 5
            time curl -i http://localhost:11434
      - name: Pull gemma2:2b
        env:
          OLLAMA_MODELS: ~/.ollama/models
        run: |
            ollama pull gemma2:2b
      - name: Output ~/.ollama/models
        run: |
            ls -alh ~/.ollama/models
      - name: Invoke gemma2:2b
        env:
          OLLAMA_MODELS: ~/.ollama/models
        run: |
            ollama run gemma2:2b "Who is the current Secretary General of the United Nations?"
