name: ollama

on:
  push:
  workflow_dispatch:

jobs:
  ollama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run Ollama Docker image and pull gemma2:2b
        run: |
          mkdir -p ~/.ollama/models
          docker run -d -v ollama:/home/runner/.ollama -p 11434:11434 --name ollama ollama/ollama
          sleep 20
          docker exec ollama ollama pull gemma2:2b
          sleep 20
          time curl -i http://localhost:11434
      - name: Invoke gemma2:2b
        run: |
          docker exec ollama ollama run gemma2:2b "Who is the current Secretary General of the United Nations?"
